# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-02 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='uploaded_files/')),
            ],
            options={
                'verbose_name': 'docfile',
                'verbose_name_plural': 'docfiles',
            },
        ),
        migrations.DeleteModel(
            name='upload_data',
        ),
    ]
